name = "clap-worker-dev"
type = "webpack"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
webpack_config = "webpack.config.js"
# route = ""
# zone_id = ""

[vars]
DEBUG = 'true'
WORKER_DOMAIN = 'http://localhost:8787'

[env.staging]
name = "clap-worker-stage"
route = "https://worker.getclaps.dev/*"
zone_id = "a0f647422a7f0fba9b734898e8a7883f"

[env.staging.vars]
DEBUG = 'true'
WORKER_DOMAIN = 'https://worker.getclaps.dev'
STRIPE_PRICE_ID = "price_1HF9nBAKMWLvHNfJlxejlWKp"
STRIPE_PUBLISHABLE_KEY = "pk_test_RqlBfBtNXivTjXiQXRtcDzd1"

[env.production]
name = "clap-worker"

[env.production.vars]
DEBUG = 'false'
WORKER_DOMAIN = 'https://worker.getclaps.net'
# STRIPE_PRICE_ID = "price_1HF9nBAKMWLvHNfJlxejlWKp"
# STRIPE_PUBLISHABLE_KEY = "pk_test_RqlBfBtNXivTjXiQXRtcDzd1"