name = "clap-worker-dev"
type = "javascript"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
kv_namespaces = [ 
  { binding = "KV_NAMESPACE", id = "13cc39b5283e4b3f9910ba08cc87d2c3", preview_id = "13cc39b5283e4b3f9910ba08cc87d2c3" }
]

[triggers]
  crons = ["0 0 * * *"]

[vars]
  WORKER_DOMAIN = 'http://localhost:8787'
  STRIPE_PRICE_ID = "price_1HF9nBAKMWLvHNfJlxejlWKp"
  STRIPE_PUBLISHABLE_KEY = "pk_test_RqlBfBtNXivTjXiQXRtcDzd1"
  CF_STORAGE_AREA__DEFAULT_KV_NAMESPACE = 'KV_NAMESPACE'

[env.staging]
  name = "clap-worker-stage"
  route = "https://worker.getclaps.dev/*"
  zone_id = "a0f647422a7f0fba9b734898e8a7883f"
  kv_namespaces = [
    { binding = "KV_NAMESPACE", id = "1b7502d1fe76494b84eb0330dd31f58b" }
  ]

  [env.staging.vars]
    WORKER_DOMAIN = 'https://worker.getclaps.dev'
    STRIPE_PRICE_ID = "price_1HF9nBAKMWLvHNfJlxejlWKp"
    STRIPE_PUBLISHABLE_KEY = "pk_test_RqlBfBtNXivTjXiQXRtcDzd1"

[env.production]
  name = "clap-worker-production"
  route = "https://worker.getclaps.app/*"
  zone_id = "8951653b87b1882bd8547e59c78fb9fb"
  kv_namespaces = [
    { binding = "KV_NAMESPACE", id = "b4a2fe0155804185a6493e257b993f0b" }
  ]

  [env.production.vars]
    WORKER_DOMAIN = 'https://worker.getclaps.app'
    STRIPE_PRICE_ID = "price_1IQ3nmJ61lhnKf1rUMT8b71Y"
    STRIPE_PUBLISHABLE_KEY = "pk_live_51HGcLVJ61lhnKf1r2Ic1uZGgvsexTk8aGpJvMB7cqIav7kvO7Fk9639sWNescJ4tQJekG4ACRPmrJGaEWTBSnKJZ00wJw7qbkN"