name = "clap-worker-dev"
type = "webpack"
account_id = "efb289061241436254219b424fcea4cf"
workers_dev = true
route = ""
zone_id = ""

[env.staging]
name = "clap-worker-stage"
# route = "*.getclaps.dev/*"

[env.staging.vars]
STRIPE_PRICE_ID = "price_1HF9nBAKMWLvHNfJlxejlWKp"
STRIPE_PUBLISHABLE_KEY = "pk_test_RqlBfBtNXivTjXiQXRtcDzd1"

[env.production]
name = "clap-worker"
# route = "*.getclaps.net/*"