name: Deploy

on:
  push:
    tags: 
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_PAT }}
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
          secrets: |
            AUTH
            FAUNA_DB_KEY
            STRIPE_SECRET_KEY
        env:
          AUTH: ${{ secrets.AUTH }}
          FAUNA_DB_KEY: ${{ secrets.FAUNA_DB_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}